import io
import re
import os
from xml.sax import saxutils
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
)
from app.utils.colors import hex_to_reportlab_color
from flask import current_app

def parse_inline_markdown(text):
    placeholders = {}
    def code_replacer(match):
        key = f"__CODE_PLACEHOLDER_{len(placeholders)}__"
        placeholders[key] = f'<font name="Courier">{saxutils.escape(match.group(1))}</font>'
        return key

    text = re.sub(r'`(.*?)`', code_replacer, text)
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
    
    for key, value in sorted(placeholders.items(), key=lambda item: len(item[0]), reverse=True):
        text = text.replace(key, value)
    return text

def create_pdf_reportlab(topic, content, theme_data, customization):
    buffer = io.BytesIO()
    supported_fonts = current_app.config['SUPPORTED_FONTS']
    font_list = list(supported_fonts.keys())
    
    title_font_name = theme_data.get('font-title', 'Roboto')
    if title_font_name not in font_list: title_font_name = 'Roboto'
    
    body_font_name = theme_data.get('font-body', 'Roboto')
    if body_font_name not in font_list: body_font_name = 'Roboto'
    
    title_font_color = hex_to_reportlab_color(theme_data.get('font-color-title', '#000000'))
    body_font_color = hex_to_reportlab_color(theme_data.get('font-color-body', '#333333'))
    
    row_colors = [colors.whitesmoke, colors.white]
    table_grid_color = body_font_color
    
    if customization.get('theme_base') == 'dark':
        row_colors = [colors.Color(0.25, 0.25, 0.25), colors.Color(0.18, 0.18, 0.18)]
        body_font_color = colors.white
        table_grid_color = colors.white

    doc = SimpleDocTemplate(buffer, pagesize=letter,
                            rightMargin=inch, leftMargin=inch,
                            topMargin=inch, bottomMargin=inch)
    
    styles = getSampleStyleSheet()
    
    normal_style = ParagraphStyle(
        name='Normal',
        fontName=body_font_name,
        fontSize=10,
        leading=14,
        textColor=body_font_color,
        spaceAfter=6,
        alignment=TA_LEFT
    )
    h1_style = ParagraphStyle(
        name='h1',
        fontName=f"{title_font_name}-Bold",
        fontSize=28,
        leading=32,
        textColor=title_font_color,
        spaceAfter=18,
        alignment=TA_LEFT
    )
    h2_style = ParagraphStyle(
        name='h2',
        fontName=f"{title_font_name}-Bold",
        fontSize=16,
        leading=20,
        textColor=title_font_color,
        spaceBefore=12,
        spaceAfter=8,
        alignment=TA_LEFT
    )
    h3_style = ParagraphStyle(
        name='h3',
        fontName=f"{body_font_name}-Bold",
        fontSize=12,
        leading=14,
        textColor=title_font_color,
        spaceBefore=10,
        spaceAfter=5,
        alignment=TA_LEFT
    )
    bullet_style = ParagraphStyle(
        name='bullet_style',
        parent=normal_style,
        leftIndent=0.3 * inch,
        firstLineIndent=-0.15 * inch,
        spaceAfter=4
    )
    code_style = ParagraphStyle(
        name='code_style',
        fontName='Courier',
        fontSize=9,
        leading=11,
        textColor=body_font_color,
        backColor=colors.Color(0.9, 0.9, 0.9),
        borderPadding=5,
        leftIndent=10,
        rightIndent=10,
        spaceBefore=6,
        spaceAfter=10,
        alignment=TA_LEFT,
        wordWrap='Longest'
    )
    if customization.get('theme_base') == 'dark':
        code_style.textColor = colors.white
        code_style.backColor = colors.Color(0.1, 0.1, 0.1)

    story = []

    if customization.get('intro_slide') == 'true':
        story.append(Spacer(1, 2 * inch))
        story.append(Paragraph(topic, h1_style))
        story.append(Spacer(1, 0.5 * inch))
        story.append(Paragraph("Generated by EduWise AI", normal_style))
        story.append(Spacer(1, 4 * inch))
        story.append(PageBreak())

    is_parsing_table = False
    table_data = []
    table_styles = []

    is_parsing_code = False
    code_buffer = []

    lines = content.split('\n')
    for line in lines:
        stripped_line = line.strip()
        robust_stripped_line = stripped_line.strip('` ')

        if stripped_line.startswith('```'):
            if is_parsing_code:
                is_parsing_code = False
                full_code_text = "<br/>".join(saxutils.escape(code_line) for code_line in code_buffer)
                story.append(Paragraph(full_code_text, code_style))
                code_buffer = []
            else:
                is_parsing_code = True
            continue

        if is_parsing_code:
            code_buffer.append(line)
            continue
        
        if is_parsing_table and not robust_stripped_line.startswith('|'):
            is_parsing_table = False
            if table_data:
                table_styles.append(('ROWBACKGROUNDS', (0, 1), (-1, -1), row_colors))
                table_styles.append(('GRID', (0, 0), (-1, -1), 1, table_grid_color))
                table_styles.append(('VALIGN', (0, 0), (-1, -1), 'TOP'))
                table = Table(table_data, colWidths=[doc.width/len(table_data[0])] * len(table_data[0]))
                table.setStyle(TableStyle(table_styles))
                story.append(table)
                story.append(Spacer(1, 0.2 * inch))
                table_data = []

        if not stripped_line:
            continue

        if robust_stripped_line.startswith('|'):
            if '---' in robust_stripped_line: continue
            if not is_parsing_table:
                is_parsing_table = True
                table_data = []
                table_styles = []
            
            cells = [parse_inline_markdown(c.strip()) for c in robust_stripped_line.split('|') if c.strip() or (robust_stripped_line.startswith('|') and robust_stripped_line.endswith('|'))]
            if cells:
                table_data.append([Paragraph(c, normal_style) for c in cells])
            continue

        if stripped_line.startswith('## '):
            story.append(Paragraph(parse_inline_markdown(stripped_line[3:]), h2_style))
        elif stripped_line.startswith('### '):
            story.append(Paragraph(parse_inline_markdown(stripped_line[4:]), h3_style))
        elif stripped_line.startswith('* '):
            story.append(Paragraph(parse_inline_markdown(stripped_line[2:]), bullet_style, bulletText='•'))
        else:
            story.append(Paragraph(parse_inline_markdown(line), normal_style))

    if is_parsing_code and code_buffer:
        full_code_text = "<br/>".join(saxutils.escape(code_line) for code_line in code_buffer)
        story.append(Paragraph(full_code_text, code_style))

    if is_parsing_table and table_data:
        table_styles.append(('ROWBACKGROUNDS', (0, 1), (-1, -1), row_colors))
        table_styles.append(('GRID', (0, 0), (-1, -1), 1, table_grid_color))
        table_styles.append(('VALIGN', (0, 0), (-1, -1), 'TOP'))
        table = Table(table_data, colWidths=[doc.width/len(table_data[0])] * len(table_data[0]))
        table.setStyle(TableStyle(table_styles))
        story.append(table)
        story.append(Spacer(1, 0.2 * inch))

    doc.build(story)
    buffer.seek(0)
    return buffer
