"""Rename filename to file_url

Revision ID: 0183ba6ffecc
Revises: f121e898898f
Create Date: 2026-04-29 12:30:53.574545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0183ba6ffecc'
down_revision = 'f121e898898f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=250), nullable=True))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=250), nullable=True))
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
